version: '3.8'

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: doc_qa_db
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-dbname}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis untuk Celery Broker
  redis:
    image: redis:7-alpine
    container_name: doc_qa_redis

  # FastAPI Web Application
  web:
    build: .
    container_name: doc_qa_api
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-dbname}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  # Celery Worker
  worker:
    build: .
    container_name: doc_qa_worker
    command: celery -A src.tasks.celery_task worker --queues=io_task --pool=threads --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER:-user}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-dbname}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_BACKEND_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  caddy:
    image: caddy:latest
    container_name: doc_qa_caddy
    restart: always
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile  # File konfigurasi Caddy
      - caddy_data:/data                  # Caddy's Data (certificate, etc)
      - caddy_config:/config              # Internal cofiguration caddy
    depends_on:
      - web

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
