"""Add indexing in model ChatMessage

Revision ID: 548195eb7e5c
Revises: a8cac02b94eb
Create Date: 2026-04-03 18:14:51.685118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '548195eb7e5c'
down_revision: Union[str, Sequence[str], None] = 'a8cac02b94eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_document_id_timestamp', 'chat_messages', ['document_id', 'timestamp'], unique=False)
    op.create_index('idx_user_id_timestamp', 'chat_messages', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_id_timestamp', table_name='chat_messages')
    op.drop_index('idx_document_id_timestamp', table_name='chat_messages')
    # ### end Alembic commands ###
