"""add_chat_evaluations

Revision ID: 9dd82fe56dfb
Revises: 579ffb82b221
Create Date: 2026-05-12 23:03:49.066121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd82fe56dfb'
down_revision: Union[str, Sequence[str], None] = '579ffb82b221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('faithfulness_score', sa.Float(), nullable=True),
    sa.Column('answer_relevancy_score', sa.Float(), nullable=True),
    sa.Column('faithfulness_reasoning', sa.Text(), nullable=True),
    sa.Column('relevancy_reasoning', sa.Text(), nullable=True),
    sa.Column('contexts', sa.JSON(), nullable=True),
    sa.Column('raw_eval_response', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_eval_status', 'chat_evaluations', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_evaluations_message_id'), 'chat_evaluations', ['message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_evaluations_message_id'), table_name='chat_evaluations')
    op.drop_index('idx_eval_status', table_name='chat_evaluations')
    op.drop_table('chat_evaluations')
    # ### end Alembic commands ###
