"""Add model ChatSession and modify model ChatMessage

Revision ID: aab1b656fcec
Revises: 548195eb7e5c
Create Date: 2026-04-03 18:33:06.366949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aab1b656fcec'
down_revision: Union[str, Sequence[str], None] = '548195eb7e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.add_column('chat_messages', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('chat_messages', sa.Column('role', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('chat_messages', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_index(op.f('idx_document_id_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('idx_user_id_timestamp'), table_name='chat_messages')
    op.create_index('idx_session_created', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.drop_constraint(op.f('chat_messages_document_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'chat_sessions', ['session_id'], ['id'])
    op.drop_column('chat_messages', 'question')
    op.drop_column('chat_messages', 'answer')
    op.drop_column('chat_messages', 'timestamp')
    op.drop_column('chat_messages', 'document_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('answer', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('chat_messages', sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_document_id_fkey'), 'chat_messages', 'documents', ['document_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_index('idx_session_created', table_name='chat_messages')
    op.create_index(op.f('idx_user_id_timestamp'), 'chat_messages', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_document_id_timestamp'), 'chat_messages', ['document_id', 'timestamp'], unique=False)
    op.drop_column('chat_messages', 'created_at')
    op.drop_column('chat_messages', 'content')
    op.drop_column('chat_messages', 'role')
    op.drop_column('chat_messages', 'session_id')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
